### PR TITLE
Fixed restart of fileupload

### LINKED ISSUE #380: 🐛 BUG: can't restart a fileupload
when a fileupload fails you can't restart it by clicking upload again.
In order to restart it (or upload something else) you currently need to close and reopen the unit.

### PR DESCRIPTION
**Pull request by fwitulski**
Restart of file upload after cancellation or error is now possible

## Description:
added reset of fileUploader status variable "isUploading", so restart of file upload is possible

Closes #380 

## Improvements
- 

## Known Issues:
_NONE_

------
_Remember to prefix your PR-Title with `⚠ WIP: ` if you still work on it.
If you have reached a final state, remove the prefix._

### CODE REVIEW

File: app/webFrontend/src/app/shared/components/upload-form/upload-form.component.ts [hunk 1]
```diff
@@ -60,6 +61,7 @@ export class UploadFormComponent implements OnInit, OnChanges {
 
     this.fileUploader.onCancelItem = () => {
       this.fileUploader.isUploading = false;
+      throw(errorCodes.upload.cancel);
```
Comment (PatrickSkowronek) [inline app/webFrontend/src/app/shared/components/upload-form/upload-form.component.ts]: You throw a new error, but what I expected was that there should not be any error when you cancel a upload, or when the upload fail. There is properly a try and catch missing.

Comment (fwitulski) [reply app/webFrontend/src/app/shared/components/upload-form/upload-form.component.ts]: okay then I missunderstood your previous comment. Will have to take a deeper look, because the cancel function comes from an external library.

**Comment by fwitulski** [comment]
Behaviour of the upload slightly changed. If you cancel a file now the next file is automatically processed, beforehand the whole upload was "paused". Is that fine?

**Comment by PatrickSkowronek** [comment]
I think that it is fine, i can't find a good reason not to stop the upload of multiple files. @d89 what do you think. What is the behavior of moodle? Should we add a cancel all button.

**Comment by PatrickSkowronek** [comment]
It's working as expected if @d89 want a "cancel all" button, we should open a new issue!
